version: '3'
services:
  db:
    container_name: ivang.runatestdb
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
  adminer:
    container_name: ivang.adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
